version: '3'

services:
  fuxchaindnode0:
    container_name: fuxchaindnode0
    image: "fuxchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-fuxchaind.log}
    volumes:
      - ./build:/fuxchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  fuxchaindnode1:
    container_name: fuxchaindnode1
    image: "fuxchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-fuxchaind.log}
    volumes:
      - ./build:/fuxchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  fuxchaindnode2:
    container_name: fuxchaindnode2
    image: "fuxchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-fuxchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fuxchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  fuxchaindnode3:
    container_name: fuxchaindnode3
    image: "fuxchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-fuxchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fuxchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

